In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('reddit_dataset.csv')
df.head()

,subreddit,id,title,selftext,score,num_comments,created_utc,flair,upvote_ratio,is_self,nsfw,author,url,sort_type,popularity_bucket
0,technology,1lvds7w,Students can’t use AI to cheat on standardized...,NaN,2,2,1.752051e+09,Artificial Intelligence,1.00,False,False,ubcstaffer123,https://www.fraserinstitute.org/commentary/stu...,new,low
1,technology,1lvdi5e,Instagram wrongly accuses some users of breach...,NaN,9,2,1.752050e+09,Social Media,1.00,False,False,zsreport,https://www.bbc.com/news/articles/cy8kjdz9nr3o,new,low
2,technology,1lvcxoa,Turkey blocks X's Grok chatbot for alleged ins...,NaN,18,3,1.752047e+09,Social Media,0.91,False,False,BreakfastTop6899,https://www.reuters.com/business/media-telecom...,new,low
3,technology,1lvai0d,GlobalFoundries to make RISC-V CPUs — fab acqu...,NaN,18,1,1.752038e+09,Hardware,0.83,False,False,jhansonxi,https://www.tomshardware.com/pc-components/cpu...,new,low
4,technology,1lv9syt,Rubio impersonation campaign underscores broad...,NaN,25,3,1.752036e+09,Artificial Intelligence,0.82,False,False,BreakfastTop6899,https://www.axios.com/2025/07/08/rubio-ai-impe...,new,low

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10047 entries, 0 to 10046
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subreddit          10047 non-null  object
 1   id                 10047 non-null  object
 2   title              10047 non-null  object
 3   selftext           1335 non-null   object
 4   score              10047 non-null  int64
 5   num_comments       10047 non-null  int64
 6   created_utc        10047 non-null  float64
 7   flair              6008 non-null   object
 8   upvote_ratio       10047 non-null  float64
 9   is_self            10047 non-null  bool
 10  nsfw               10047 non-null  bool
 11  author             9641 non-null   object
 12  url                10047 non-null  object
 13  sort_type          10047 non-null  object
 14  popularity_bucket  10047 non-null  object
dtypes: bool(2), float64(2), int64(2), object(9)
memory usage: 1.0+ MB

In [6]:
df.describe()

               score  num_comments   created_utc  upvote_ratio
count   10047.000000  10047.000000  1.004700e+04  10047.000000
mean    42127.680402   1548.207823  1.665287e+09      0.821978
std     45791.415401   2682.173433  9.222974e+07      0.184150
min         0.000000      0.000000  1.407798e+09      0.060000
25%       127.000000     31.000000  1.588867e+09      0.810000
50%     38868.000000    824.000000  1.682469e+09      0.890000
75%     72902.500000   2252.500000  1.751457e+09      0.930000
max    439029.000000  88172.000000  1.752052e+09      1.000000

In [7]:
df.head()

,subreddit,id,title,selftext,score,num_comments,created_utc,flair,upvote_ratio,is_self,nsfw,author,url,sort_type,popularity_bucket
0,technology,1lvds7w,Students can’t use AI to cheat on standardized...,NaN,2,2,1.752051e+09,Artificial Intelligence,1.00,False,False,ubcstaffer123,https://www.fraserinstitute.org/commentary/stu...,new,low
1,technology,1lvdi5e,Instagram wrongly accuses some users of breach...,NaN,9,2,1.752050e+09,Social Media,1.00,False,False,zsreport,https://www.bbc.com/news/articles/cy8kjdz9nr3o,new,low
2,technology,1lvcxoa,Turkey blocks X's Grok chatbot for alleged ins...,NaN,18,3,1.752047e+09,Social Media,0.91,False,False,BreakfastTop6899,https://www.reuters.com/business/media-telecom...,new,low
3,technology,1lvai0d,GlobalFoundries to make RISC-V CPUs — fab acqu...,NaN,18,1,1.752038e+09,Hardware,0.83,False,False,jhansonxi,https://www.tomshardware.com/pc-components/cpu...,new,low
4,technology,1lv9syt,Rubio impersonation campaign underscores broad...,NaN,25,3,1.752036e+09,Artificial Intelligence,0.82,False,False,BreakfastTop6899,https://www.axios.com/2025/07/08/rubio-ai-impe...,new,low

In [ ]:
print(df['selftext'].unique())
print(df['selftext'].value_counts())

In [ ]:
# analyis of the selftext column: Is it just the same as title field?
# Show only rows where selftext is not missing
df_with_selftext = df[df['selftext'].notna() & (df['selftext'].str.strip() != '')]

# View first few rows
df_with_selftext[['title', 'selftext']].head(10)

,title,selftext
813,Impromptu Guinness Chugging Contest at the Nat...,Badlands wins by a sip at the Gaf West in Hell...
859,Wimbledon Round 1: Arthur Rinderknech has knoc...,Arthur Rinderknech has knocked out third seed ...
872,The WNBA is expanding to 18 teams over the nex...,"Cleveland will begin play in 2028, Detroit in ..."
877,Crazy flip in Argentina's TC Pick Up,Driver Agustín Martínez is concious and was ta...
883,15yr old Australian skateboarder Arisa Trew br...,"At just 15 years old, Arisa Trew has once agai..."
892,Kishane Thompson of Jamaica has run the sixth-...,Thompson is firmly in the mix for gold at the ...
894,“Best day of my life” - Dunne delivers on F1 d...,https://www.bbc.com/sport/formula1/articles/cj...
914,15 years ago today in 2010 - Uruguay beat Sout...,La Celeste would advance to the World Cup semi...
930,New York Mets Pitcher Richard Lovelady Request...,What's in a name?
941,"For The First Time In History, the Reigning NB...",Canadian athletes are having a good year going...

In [15]:
df[df['author'].isna()].head()

,subreddit,id,title,selftext,score,num_comments,created_utc,flair,upvote_ratio,is_self,nsfw,author,url,sort_type,popularity_bucket
467,technology,1lo7wfm,How Signal President Meredith Whittaker Took o...,NaN,34,16,1.751291e+09,Privacy,0.72,False,False,NaN,https://time.com/collections/time100-companies...,new,low
677,technology,1lkzev6,Public Signal Backups Testing (Android; iOS an...,NaN,3,2,1.750942e+09,Security,0.61,False,False,NaN,https://community.signalusers.org/t/public-sig...,new,low
1145,sports,1l3je9h,Fatal crash before the Baja 500 leaves one dea...,NaN,45,5,1.749077e+09,:racing: Motorsports,0.85,False,False,NaN,https://el-mexicano.com.mx/Noticia/Policiaca/7...,new,low
1250,sports,1kv061s,"Real Madrid bid farewell to Carlo Ancelotti, t...",NaN,4039,49,1.748172e+09,:soccer: Soccer,0.97,False,False,NaN,https://v.redd.it/jptrovskww2f1,new,medium
1371,sports,1kldw7j,Oswaldo Cabrera serious injury on slide attempt,NaN,1019,149,1.747113e+09,:baseball: Baseball,0.93,False,True,NaN,https://v.redd.it/rda2d52ggh0f1,new,medium

In [29]:
# Exact match
print(df['flair'].value_counts().get('ADBLOCK WARNING', 0))

11

In [20]:
df['selftext'] = df['selftext'].fillna('')   # Keep blank text if missing

df['flair'] = df['flair'].fillna('None')     # Fill missing flair with "none" label (as no label assigned)
df['author'] = df['author'].fillna('[deleted]')

df.drop_duplicates(subset='id', inplace=True)

# Create a new feature (hour) from timestamp
df['created_hour'] = pd.to_datetime(df['created_utc'], unit='s').dt.hour
df.drop(columns=['created_utc'], inplace=True)

In [21]:
df.head()

,subreddit,id,title,selftext,score,num_comments,flair,upvote_ratio,is_self,nsfw,author,url,sort_type,popularity_bucket,created_hour
0,technology,1lvds7w,Students can’t use AI to cheat on standardized...,,2,2,Artificial Intelligence,1.00,False,False,ubcstaffer123,https://www.fraserinstitute.org/commentary/stu...,new,low,8
1,technology,1lvdi5e,Instagram wrongly accuses some users of breach...,,9,2,Social Media,1.00,False,False,zsreport,https://www.bbc.com/news/articles/cy8kjdz9nr3o,new,low,8
2,technology,1lvcxoa,Turkey blocks X's Grok chatbot for alleged ins...,,18,3,Social Media,0.91,False,False,BreakfastTop6899,https://www.reuters.com/business/media-telecom...,new,low,7
3,technology,1lvai0d,GlobalFoundries to make RISC-V CPUs — fab acqu...,,18,1,Hardware,0.83,False,False,jhansonxi,https://www.tomshardware.com/pc-components/cpu...,new,low,5
4,technology,1lv9syt,Rubio impersonation campaign underscores broad...,,25,3,Artificial Intelligence,0.82,False,False,BreakfastTop6899,https://www.axios.com/2025/07/08/rubio-ai-impe...,new,low,4

In [30]:
df.isna().sum()

subreddit            0
id                   0
title                0
selftext             0
score                0
num_comments         0
flair                0
upvote_ratio         0
is_self              0
nsfw                 0
author               0
url                  0
sort_type            0
popularity_bucket    0
created_hour         0
dtype: int64

In [ ]:
print(df['flair'].nunique())
print(df['author'].nunique())
print(df['subreddit'].nunique())

189
5032
7

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10047 entries, 0 to 10046
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subreddit          10047 non-null  object
 1   id                 10047 non-null  object
 2   title              10047 non-null  object
 3   selftext           10047 non-null  object
 4   score              10047 non-null  int64
 5   num_comments       10047 non-null  int64
 6   flair              10047 non-null  object
 7   upvote_ratio       10047 non-null  float64
 8   is_self            10047 non-null  bool
 9   nsfw               10047 non-null  bool
 10  author             10047 non-null  object
 11  url                10047 non-null  object
 12  sort_type          10047 non-null  object
 13  popularity_bucket  10047 non-null  object
 14  created_hour       10047 non-null  int32
dtypes: bool(2), float64(1), int32(1), int64(2), object(9)
memory usage: 1000.9+ KB

In [35]:
df.nunique()

subreddit                7
id                   10047
title                 9985
selftext              1326
score                 6822
num_comments          3703
flair                  189
upvote_ratio            95
is_self                  2
nsfw                     2
author                5032
url                  10014
sort_type                2
popularity_bucket        3
created_hour            24
dtype: int64